---
- hosts: packager
  vars:
      php_version: 8.2
      timezone: Europe/Moscow
      composer_hash: 55ce33d7678c5a611085589f1f3ddf8b3c52d662cd01d4ba75c0ee0459970c2200a51f492d557530c71c15d8dba01eae
      composer_path: /usr/local/bin/composer
      php_post_max_size: 25M
      php_upload_max_filesize: 25M
      php_modules: 
        - xml
        - mbstring
        - mysqlnd
        - curl
        - pdo

  roles:
    - common
    - php-fpm
    - openvpn
    - fail2ban
    - role: iptables
      app: packager
    - zabbix-agent
    - nginx
    - role: mysql
      service: packager
    - graylog