- name: Create iptables rules directory
  become: true
  file:
    path: /etc/iptables
    state: directory

- name: Copy iptables rules
  become: true
  template:
    src: templates/{{ app }}.rules.v4.j2
    dest: /etc/iptables/rules.v4

- name: Apply iptables rules
  become: true
  shell:  iptables-restore < /etc/iptables/rules.v4

- name: Install iptables-persistent
  become: true
  apt: 
    name:
      - iptables-persistent
    update_cache: yes 
    state: latest

# - name: Copy restore script 
#   become: true
#   template: 
#     src: templates/restore.sh
#     dest: /etc/network/if-up.d/00-iptables

# - name: Set chmod at restore script
#   become: true
#   shell: chmod +x /etc/network/if-up.d/00-iptables