- name: Create iptables rules directory
  become: true
  file:
    path: /etc/iptables
    state: directory

- name: Copy iptables rules
  become: true
  template:
    src: templates/{{ app }}.rules.v4.j2
    dest: /etc/iptables/rules.v4
  register: change_rules

- name: Apply iptables rules
  become: true
  shell:  iptables-restore < /etc/iptables/rules.v4
  when: change_rules.changed

- name: Install iptables-persistent
  become: true
  apt: 
    name:
      - iptables-persistent
    update_cache: yes 
    state: latest