
# tasks file for graylog

---
- name: Install required package
  become: true
  apt:
    deb: "{{ graylog_sidecar_package }}"
    state: present
  tags:
    - graylog-sidecar

- name: Update and upgrade apt packages
  become: true
  apt:
    upgrade: yes
    update_cache: yes

- name: Install graylog-sidecar
  become: true
  apt:
    name: graylog-sidecar
    state: latest

- name: Write config file
  become: true
  notify:
    - Restart graylog-sidecar
  template:
    src: config.j2
    dest: /etc/graylog/sidecar/sidecar.yml
    owner: root
    group: root
    mode: u=rw,g=r,o=r
  tags:
    - graylog-sidecar

- name: Write service file
  become: true
  notify:
    - Restart graylog-sidecar
  template:
    src: service.j2
    dest: /etc/systemd/system/graylog-sidecar.service
    owner: root
    group: root
    mode: u=rw,g=r,o=r
  tags:
    - graylog-sidecar

- name: apt-transport-https
  become: true
  apt:
    name: apt-transport-https
    state: latest

- name: Copy deb-package filebear
  become: true
  copy:
    src: '{{ graylog_filebeat_package }}'
    dest: '{{ filebeat_remote }}'

- name: Install filebeat
  become: true
  apt:
    deb: '{{ filebeat_remote }}'
    state: present

- name: Delete deb-package filebeat
  become: true
  file:
    state: absent
    path: '{{ filebeat_remote }}'

- name: Start graylog-sidecar service
  become: true
  systemd:
    name: graylog-sidecar
    state: started
    daemon_reload: True
    masked: False
    enabled: True
  tags:
    - graylog-sidecar

- name: Start filebeat service
  become: true
  systemd:
    name: filebeat
    state: started
    daemon_reload: True
    masked: False
    enabled: True
  notify:
    - Restart graylog-sidecar