- name: Install openvpn
  become: true
  apt: 
    name:
      - openvpn

- name: Configure openvpn
  become: true
  template:
    src: templates/{{ hostname }}.ovpn
    dest: /etc/openvpn/testvpn.conf
  notify:
    - enable openvpn
    - restart openvpn

- name: Add sip ip to hosts file
  become: true
  lineinfile:
    path: /etc/hosts
    regexp: 'sip.example.com'
    line: "127.0.0.1 'sip.example.com'"

